[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-dead_strip",
    "-C", "opt-level=z",
    "-C", "codegen-units=1"
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-dead_strip",
    "-C", "opt-level=z",
    "-C", "codegen-units=1"
]
